#!/usr/bin/env python
import argparse
import sys
import config

import backup_preferences
import backup_system_preferences
import restore_preferences
import restore_system_preferences


def backup():
    backup_system_preferences.backup()
    backup_preferences.backup()


def restore():
    restore_system_preferences.restore()
    restore_preferences.restore()


if __name__ == '__main__':
    PARSER = argparse.ArgumentParser(
        prog="macprefs", description='Backup and restore mac system preferences.')
    SUBPARSERS = PARSER.add_subparsers(title="commands", metavar='')
    BACKUP_PARSER = SUBPARSERS.add_parser(
        'backup', help="Backup mac preferences to " + config.BACKUP_DIR)
    BACKUP_PARSER.set_defaults(func=backup)
    RESTORE_PARSER = SUBPARSERS.add_parser(
        'restore', help="Restore mac preferences from " + config.BACKUP_DIR)
    RESTORE_PARSER.set_defaults(func=restore)
    if len(sys.argv) == 1:
        PARSER.print_help()
        sys.exit(1)
    ARGS = PARSER.parse_args()
    if ARGS.func is not None:
        ARGS.func()
