#!/usr/bin/env python
import argparse
import sys
import config

import preferences
import shared_file_lists
import system_preferences


def backup():
    system_preferences.backup()
    preferences.backup()
    shared_file_lists.backup()


def restore():
    system_preferences.restore()
    preferences.restore()
    shared_file_lists.restore()


if __name__ == '__main__':
    backup_dir = config.get_macprefs_dir()
    parser = argparse.ArgumentParser(
        prog="macprefs", description='Backup and restore mac system preferences.')
    subparsers = parser.add_subparsers(title="commands", metavar='')
    backup_parser = subparsers.add_parser(
        'backup', help="Backup mac preferences to " + backup_dir)
    backup_parser.set_defaults(func=backup)
    restore_parser = subparsers.add_parser(
        'restore', help="Restore mac preferences from " + backup_dir)
    restore_parser.set_defaults(func=restore)
    if len(sys.argv) == 1:
        parser.print_help()
        sys.exit(0)
    args = parser.parse_args()
    if args.func is not None:
        args.func()
